// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_dotnet_core.Models;

#nullable disable

namespace backend_dotnet_core.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20231102134010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_dotnet_core.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("building_managing_relationships")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("business_society")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("competency_class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("complex_problem_solving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("course_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("course_comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("course_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("creative_thinking")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("culture_identity_society")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("digital_fluency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("effective_communication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ethics_values")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fostering_effective_collaboration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("future_intelligence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("inquisitive_spirit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mapped_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prototyping_design")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reasoning_interpretation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("resilience_grit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("science_technology_society")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("self_awareness_self_management")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("social_interpersonal_communication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
